Trigger user caching.
fabric8-analytics/f8a-stacks-report pull request #214
Opened 2021-07-06 10:57 UTC by jparsai

2021-07-07 06:08 UTC, yzainee requested changes
you need to add secrets in template file for APP_SECRET_KEY

2021-07-07 06:35 UTC, jparsai commented
> you need to add secrets in template file for APP_SECRET_KEY

I am using an existing secret
https://github.com/fabric8-analytics/f8a-stacks-report/blob/d8770b0745bc4273a14fa8a8b1465f2ba8825712/openshift/template.yaml#L205

2021-07-07 06:36 UTC, yzainee submitted a review, later dismissed

2021-07-23 10:31 UTC, yzainee approved these changes
LGTM

2021-07-23 10:31 UTC, merged